"""Isolated PPT Template Library V1 experiment.

The source decks are never opened for writing.  PowerPoint itself renders every
preview; python-pptx is used only to inventory OOXML objects in those decks.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import zipfile
from io import BytesIO
from collections import Counter
from pathlib import Path

from PIL import Image, ImageDraw
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "outputs" / "ppt_template_library_v1"
SOURCES = {
    "fujian": ROOT / "files" / "福建国核智慧楼宇建设方案.pptx",
    "industrial_park": ROOT / "files" / "工业园综合智慧能源解决方案.pptx",
    "jiamusi": ROOT / "files" / "佳木斯大学综合能源方案.pptx",
    "comking_company": ROOT / "files" / "康晋电气公司介绍2026政府版.pptx",
}


def shape_kind(shape):
    mapping = {
        MSO_SHAPE_TYPE.PICTURE: "picture",
        MSO_SHAPE_TYPE.TABLE: "table",
        MSO_SHAPE_TYPE.CHART: "chart",
        MSO_SHAPE_TYPE.GROUP: "group",
        MSO_SHAPE_TYPE.LINE: "line",
        MSO_SHAPE_TYPE.AUTO_SHAPE: "shape",
        MSO_SHAPE_TYPE.TEXT_BOX: "text_box",
        MSO_SHAPE_TYPE.PLACEHOLDER: "placeholder",
    }
    return mapping.get(shape.shape_type, str(shape.shape_type))


def walk_shapes(shapes, path=""):
    """Yield shapes including group children, with a stable source path."""
    for index, shape in enumerate(shapes):
        current = f"{path}/{index}" if path else str(index)
        yield current, shape
        if shape_kind(shape) == "group":
            yield from walk_shapes(shape.shapes, current)


def text_summary(shape):
    if not getattr(shape, "has_text_frame", False):
        return None
    text = " ".join(p.text.strip() for p in shape.text_frame.paragraphs if p.text.strip())
    if not text:
        return None
    fonts = []
    for paragraph in shape.text_frame.paragraphs:
        for run in paragraph.runs:
            if run.font.name:
                fonts.append(run.font.name)
    return {"text": text[:180], "font_names": sorted(set(fonts))}


def inventory(source: Path):
    prs = Presentation(source)
    fonts, kinds, slide_rows = Counter(), Counter(), []
    for idx, slide in enumerate(prs.slides, 1):
        row = {"slide": idx, "shapes": [], "counts": Counter(), "text_samples": []}
        for shape in slide.shapes:
            kind = shape_kind(shape)
            kinds[kind] += 1
            row["counts"][kind] += 1
            item = {"kind": kind, "name": shape.name, "x": shape.left, "y": shape.top,
                    "w": shape.width, "h": shape.height}
            text = text_summary(shape)
            if text:
                item.update(text)
                row["text_samples"].append(text["text"])
                fonts.update(text["font_names"])
            if kind == "picture":
                item["aspect_ratio"] = round(shape.width / shape.height, 3) if shape.height else None
            row["shapes"].append(item)
        row["counts"] = dict(row["counts"])
        slide_rows.append(row)
    theme = {"available": bool(getattr(prs, "slide_master", None)), "masters": len(prs.slide_masters),
             "layouts_per_master": [len(master.slide_layouts) for master in prs.slide_masters]}
    return {
        "source": source.name, "slide_count": len(prs.slides),
        "page_size_inches": {"width": round(prs.slide_width / 914400, 3), "height": round(prs.slide_height / 914400, 3)},
        "theme_and_master": theme, "font_frequency": fonts.most_common(20),
        "shape_frequency": kinds, "slides": slide_rows,
    }


def render_with_powerpoint(pptx: Path, target: Path):
    target.mkdir(parents=True, exist_ok=True)
    # SaveAs(18) does not reliably replace an existing same-name export folder.
    # This directory is generated by this experiment only, never a source deck.
    export_dir = target / "slide"
    if export_dir.exists():
        shutil.rmtree(export_dir)
    command = ["powershell", "-ExecutionPolicy", "Bypass", "-File", str(ROOT / "scripts" / "render_pptx_windows.ps1"),
               "-InputPath", str(pptx), "-OutputDir", str(target)]
    result = subprocess.run(command, cwd=ROOT, text=True, encoding="utf-8", errors="replace", capture_output=True, timeout=300)
    if result.returncode:
        raise RuntimeError(f"PowerPoint render failed for {pptx.name}: {result.stderr or result.stdout}")
    # PowerPoint SaveAs(18) creates a directory named after the requested
    # basename, then puts one PNG per slide inside it.
    return sorted((path for path in target.rglob("*") if path.suffix.lower() == ".png"), key=lambda p: p.name)


def contact_sheet(images, output: Path, cols=4, width=360):
    if not images:
        raise RuntimeError("No PowerPoint-rendered PNGs were produced")
    thumbs = []
    for path in images:
        with Image.open(path) as im:
            ratio = im.height / im.width
            thumb = im.convert("RGB").resize((width, round(width * ratio)))
            thumbs.append((path, thumb))
    cell_h = max(im.height for _, im in thumbs) + 32
    rows = (len(thumbs) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * width, rows * cell_h), "white")
    draw = ImageDraw.Draw(sheet)
    for i, (path, im) in enumerate(thumbs):
        x, y = (i % cols) * width, (i // cols) * cell_h
        sheet.paste(im, (x, y + 22))
        draw.text((x + 6, y + 4), path.name, fill="black")
    sheet.save(output)


def analysis_markdown(key, data):
    freq = data["shape_frequency"]
    image_slides = sum(1 for slide in data["slides"] if slide["counts"].get("picture"))
    return f"""# {key} 视觉审计

## 可验证的结构事实

- 页数：{data['slide_count']}；页面比例：{data['page_size_inches']['width']} × {data['page_size_inches']['height']} 英寸。
- 母版：{data['theme_and_master']['masters']} 个；每个母版布局数：{data['theme_and_master']['layouts_per_master']}。
- 页面对象统计：{dict(freq)}；含图片页面：{image_slides}/{data['slide_count']}。
- 可解析的字体出现频次：{data['font_frequency'][:12]}。主题、母版、图片裁切、透明度和阴影保留在原始 OOXML / 真实 PowerPoint 渲染中，不能仅以解析值替代视觉判断。

## 初步页面语言（以真实 contact sheet 复核）

- 封面、章节、图文、架构/流程和价值页均以真实页面截图为准标记；本实验不把解析出的形状统计误称为视觉结论。
- 标题、页脚、Logo、背景装饰、图片遮罩/裁切和配色是继承资产，prototype 内容替换时均不重画。
- 详见 `slide_inventory.json` 中每一页的文字样本、对象类型和矩形位置；后续 catalog 仅引用真实 slide 编号。
"""


def run_analysis():
    for key, source in SOURCES.items():
        if not source.exists():
            raise FileNotFoundError(source)
        directory = OUT / "source_analysis" / key
        directory.mkdir(parents=True, exist_ok=True)
        data = inventory(source)
        (directory / "slide_inventory.json").write_text(json.dumps(data, ensure_ascii=False, indent=2, default=dict), encoding="utf-8")
        (directory / "design_analysis.md").write_text(analysis_markdown(key, data), encoding="utf-8")
        pngs = render_with_powerpoint(source, directory / "slides")
        contact_sheet(pngs, directory / "contact_sheet.png")
        print(f"analysed {key}: {data['slide_count']} slides, {len(pngs)} PowerPoint PNGs")


PROTOTYPES = [
    ("COVER_HERO_IMAGE", "jiamusi", 1, "full-bleed hero cover"),
    ("SECTION_URBAN", "jiamusi", 3, "chapter divider / section"),
    ("IMAGE_TEXT_CASE", "jiamusi", 5, "large visual with annotated plan"),
    ("PROCESS_HORIZONTAL", "jiamusi", 6, "horizontal process / workflow"),
    ("CAPABILITY_CARDS", "jiamusi", 8, "multi-capability card grid"),
    ("PLATFORM_SCREENSHOT", "jiamusi", 12, "platform and mobile screen showcase"),
    ("METRICS_CARD", "jiamusi", 14, "KPI / value metric card system"),
    ("BENEFIT_COMPARISON", "jiamusi", 15, "comparison and benefit bars"),
    ("CASE_STUDY_IMAGE_TEXT", "jiamusi", 21, "two screenshots plus narrative"),
    ("ARCHITECTURE_CENTER", "fujian", 27, "layered platform architecture"),
    ("SYSTEM_DASHBOARD", "fujian", 16, "dashboard plus operating scene"),
    ("EXECUTIVE_CLOSE", "jiamusi", 25, "corporate closing / end page"),
]


def clone_selected_slides(source: Path, output: Path, selected: list[int]):
    """Package-level slide clone: change only presentation.xml's slide list.

    No shape is recreated and no source PPTX is opened for writing.  Orphaned
    relationships remain intentionally: PowerPoint ignores them, while every
    kept slide still points at its original media/theme/master package parts.
    """
    with zipfile.ZipFile(source) as zin:
        xml = zin.read("ppt/presentation.xml")
        from lxml import etree
        root = etree.fromstring(xml)
        ns = {"p": "http://schemas.openxmlformats.org/presentationml/2006/main"}
        ids = root.xpath("p:sldIdLst/p:sldId", namespaces=ns)
        if not all(1 <= n <= len(ids) for n in selected):
            raise ValueError(f"invalid source slide selection: {selected}")
        wanted = {ids[n - 1] for n in selected}
        for item in ids:
            if item not in wanted:
                item.getparent().remove(item)
        altered = etree.tostring(root, xml_declaration=True, encoding="UTF-8", standalone=True)
        selected_rel_ids = {item.get("{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id") for item in wanted}
        rels_root = etree.fromstring(zin.read("ppt/_rels/presentation.xml.rels"))
        for rel in list(rels_root):
            if rel.get("Type", "").endswith("/slide") and rel.get("Id") not in selected_rel_ids:
                rels_root.remove(rel)
        altered_rels = etree.tostring(rels_root, xml_declaration=True, encoding="UTF-8", standalone=True)
        output.parent.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                if item.filename == "ppt/presentation.xml":
                    zout.writestr(item, altered)
                elif item.filename == "ppt/_rels/presentation.xml.rels":
                    zout.writestr(item, altered_rels)
                else:
                    zout.writestr(item, zin.read(item.filename))


def write_text_preserving_style(shape, value: str):
    texts = list(shape._element.iter("{http://schemas.openxmlformats.org/drawingml/2006/main}t"))
    if not texts:
        return False
    texts[0].text = value
    for node in texts[1:]:
        node.text = ""
    return True


def replace_picture_media(deck: Path, slide_index: int, image: Path):
    """Replace a picture's media bytes while retaining its crop and geometry."""
    prs = Presentation(deck)
    pictures = [s for s in prs.slides[slide_index].shapes if shape_kind(s) == "picture"]
    if not pictures:
        return False
    picture = pictures[-1]  # never use a header logo as the test image slot
    rid = picture._element.blip_rId
    if not rid:
        return False
    media_name = str(picture.part.rels[rid].target_part.partname).lstrip("/")
    if Path(media_name).suffix.lower() != image.suffix.lower():
        return False
    with zipfile.ZipFile(deck) as zin:
        temp = deck.with_suffix(".tmp")
        with zipfile.ZipFile(temp, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                zout.writestr(item, image.read_bytes() if item.filename == media_name else zin.read(item.filename))
    temp.replace(deck)
    return True


def make_catalog():
    catalog_dir = OUT / "catalog"
    templates = OUT / "ppt_templates"
    previews = catalog_dir / "prototype_previews"
    catalog_dir.mkdir(parents=True, exist_ok=True)
    records = []
    for name, family, slide, use in PROTOTYPES:
        target = templates / f"{name.lower()}.pptx"
        clone_selected_slides(SOURCES[family], target, [slide])
        render_with_powerpoint(target, previews / name.lower())
        preview = next((previews / name.lower()).rglob("*.png"))
        record = {
            "prototype": name, "style_family": "COMKING_LIGHT_BLUE",
            "source_ppt": SOURCES[family].name, "source_key": family, "source_slide": slide,
            "preview": str(preview.relative_to(OUT)).replace("\\", "/"),
            "content_capacity": "title ≤ 2 lines; body follows the original slide's visible text regions",
            "slots": ["TITLE", "BODY", "IMAGE_MAIN"] if "IMAGE" in name or "SCREEN" in name else ["TITLE", "BODY"],
            "must_preserve": ["logo", "footer/header strip", "brand background", "decorative geometry", "original image crop frame"],
            "best_for": use,
        }
        records.append(record)
    (catalog_dir / "layout_catalog.json").write_text(json.dumps(records, ensure_ascii=False, indent=2), encoding="utf-8")
    lines = ["# Template Library V1 — 真实页面原型目录", "", "所有原型均是从指定公司源 PPT 的真实 slide 做包级克隆；不是 python-pptx 重绘。", ""]
    for r in records:
        lines += [f"## {r['prototype']}", "", f"- 真实来源：`{r['source_key']}` 第 {r['source_slide']} 页（`{r['source_ppt']}`）",
                  f"- 适用表达：{r['best_for']}", f"- Slots：{', '.join(r['slots'])}",
                  f"- 保留资产：{', '.join(r['must_preserve'])}", f"- 预览：`{r['preview']}`", ""]
    (catalog_dir / "layout_catalog.md").write_text("\n".join(lines), encoding="utf-8")
    shutil.copy2(catalog_dir / "layout_catalog.json", OUT / "layout_catalog.json")
    shutil.copy2(catalog_dir / "layout_catalog.md", OUT / "layout_catalog.md")
    return records


V2_SOURCE_SLIDES = [1, 5, 6, 14, 21]

# Explicit, source-pinned maps. shape_id is read from the original slide and
# is retained by the package-level clone; source_slide + shape_id is therefore
# stronger than text length/name guessing.
V2_SLOT_MAPS = {
    "cover_hero_image": {"prototype": "COVER_HERO_IMAGE", "source_slide": 1, "preserve": [2, 9], "images": [],
        "slots": [(7, "TITLE", "医院园区高可靠供电与智慧配电改造方案", 26, 2, True),
                  (8, "SUBTITLE", "守护生命供电防线 · 可视、可控、可预警", 32, 1, False),
                  (19, "CALLOUT_1", "可靠供电", 8, 1, False), (20, "CALLOUT_1_DETAIL", "核心负荷", 8, 1, False),
                  (23, "CALLOUT_2", "预警联动", 8, 1, False), (24, "CALLOUT_2_DETAIL", "风险前置", 8, 1, False),
                  (27, "CALLOUT_3", "智慧运维", 8, 1, False), (28, "CALLOUT_3_DETAIL", "闭环管理", 8, 1, False)]},
    "image_text_case": {"prototype": "IMAGE_TEXT_CASE", "source_slide": 5, "preserve": [], "images": [(35, "IMAGE_MAIN", "image-002.jpg"), (5, "IMAGE_SECONDARY", "image-001.jpg")],
        "slots": [(46, "TITLE", "配电房全域感知与系统集成", 18, 2, True)]},
    "process_horizontal": {"prototype": "PROCESS_HORIZONTAL", "source_slide": 6, "preserve": [], "images": [(12, "IMAGE_MAIN", "image-001.jpg"), (9, "UNUSED_SOURCE_GRAPHIC", None)],
        "slots": [(2, "BODY", "监测采集 → 异常识别 → 分级告警 → 工单处置 → 复盘优化", 36, 3, True),
                  (7, "BODY_1", "多维状态采集", 16, 2, False), (10, "BODY_2", "预警与联动处置", 16, 2, False),
                  (13, "CALLOUT_1", "医院供电安全闭环", 12, 1, False)]},
    "metrics_card": {"prototype": "METRICS_CARD", "source_slide": 14, "preserve": [], "images": [],
        "slots": [(77, "TITLE", "医院改造价值与测算边界", 20, 1, True),
                  (24, "METRIC_1_LABEL", "供电风险前置", 12, 1, True), (25, "METRIC_1_BODY", "围绕核心负荷建立监测与预警。", 25, 3, False), (27, "METRIC_1_TAG", "状态可视", 8, 1, False),
                  (30, "METRIC_2_LABEL", "运维协同提效", 12, 1, True), (31, "METRIC_2_VALUE", "待确认", 6, 1, False), (32, "METRIC_2_BODY", "巡检、告警与工单形成闭环。", 25, 2, False), (34, "METRIC_2_TAG", "闭环运维", 8, 1, False),
                  (37, "METRIC_3_LABEL", "能耗精细管理", 12, 1, True), (38, "METRIC_3_VALUE", "待确认", 6, 1, False), (39, "METRIC_3_BODY", "以现场负荷与电价数据深化测算。", 25, 2, False), (41, "METRIC_3_TAG", "持续优化", 8, 1, False),
                  (45, "CALLOUT_1", "实施边界确认", 12, 1, False), (46, "CALLOUT_1_VALUE", "待确认", 6, 1, False), (47, "CALLOUT_1_BODY", "负荷、台账、电价等参数待核实。", 25, 1, False),
                  (54, "CALLOUT_2", "现场勘察深化", 12, 1, False), (61, "CALLOUT_2_VALUE", "待确认", 6, 1, False), (65, "CALLOUT_2_BODY", "设备配置与投资边界待确认。", 25, 1, False),
                  (74, "CALLOUT_3", "运行保障", 12, 1, False), (75, "CALLOUT_3_VALUE", "待确认", 6, 1, False), (76, "CALLOUT_3_BODY", "以医院核心负荷连续供电为先。", 25, 1, False)]},
    "case_study_image_text": {"prototype": "CASE_STUDY_IMAGE_TEXT", "source_slide": 21, "preserve": [], "images": [(7, "IMAGE_MAIN", "image-002.jpg"), (9, "IMAGE_SECONDARY", "image-004.jpg")],
        "slots": [(11, "TITLE", "智慧能源管理平台架构", 18, 1, True),
                  (6, "BODY", "设备层采集电力与动环数据；边缘网关统一汇聚；平台提供监控、告警、分析与运维协同。项目参数及实施范围待现场确认。", 66, 4, True)]},
}


def inspect_v2_sources():
    """Create an exact, group-aware source shape inventory for slot mapping."""
    source = SOURCES["jiamusi"]
    prs = Presentation(source)
    output = OUT / "v2" / "slot_maps" / "source_shape_inventory.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for slide_no in V2_SOURCE_SLIDES:
        slide = prs.slides[slide_no - 1]
        shapes = []
        for path, shape in walk_shapes(slide.shapes):
            text = text_summary(shape)
            shapes.append({"path": path, "shape_id": shape.shape_id, "name": shape.name,
                           "kind": shape_kind(shape), "x": shape.left, "y": shape.top,
                           "w": shape.width, "h": shape.height, "text": text["text"] if text else None})
        rows.append({"source_slide": slide_no, "shapes": shapes})
    output.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")
    print(output)


def clear_shape_text(shape):
    for node in shape._element.iter("{http://schemas.openxmlformats.org/drawingml/2006/main}t"):
        node.text = ""


def write_slot_maps():
    directory = OUT / "v2" / "slot_maps"
    directory.mkdir(parents=True, exist_ok=True)
    for filename, spec in V2_SLOT_MAPS.items():
        slots = []
        for shape_id, role, value, max_chars, max_lines, required in spec["slots"]:
            slots.append({"slot_id": role, "role": role, "shape_id": shape_id,
                          "xml_selector": f".//p:cNvPr[@id='{shape_id}']", "type": "text",
                          "editable": True, "preserve_style": True, "max_chars": max_chars,
                          "max_lines": max_lines, "required": required,
                          "fallback_behavior": "clear when unused; reject content above capacity"})
        for shape_id, role, media in spec["images"]:
            slots.append({"slot_id": role, "role": role, "shape_id": shape_id,
                          "xml_selector": f".//p:cNvPr[@id='{shape_id}']", "type": "picture",
                          "editable": True, "preserve_style": True, "max_chars": None,
                          "max_lines": None, "required": True,
                          "fallback_behavior": "fail page if relationship-level replacement fails", "replacement": media})
        for shape_id in spec["preserve"]:
            slots.append({"slot_id": f"PRESERVE_{shape_id}", "role": "LOGO_OR_BRAND_BACKGROUND", "shape_id": shape_id,
                          "type": "brand", "editable": False, "preserve_style": True,
                          "max_chars": None, "max_lines": None, "required": True,
                          "fallback_behavior": "never clear or replace"})
        payload = {"prototype": spec["prototype"], "source_ppt": SOURCES["jiamusi"].name,
                   "source_slide": spec["source_slide"], "selector_strategy": "source slide number + shape_id; group-aware traversal",
                   "slots": slots, "clear_rule": "Every text-bearing shape not declared as a slot or preserve element is cleared."}
        (directory / f"{filename}.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def target_shape_by_id(slide, shape_id):
    for _, shape in walk_shapes(slide.shapes):
        if shape.shape_id == shape_id:
            return shape
    raise KeyError(f"shape id {shape_id} not found")


def image_bytes_for_target(image: Path, media_name: str):
    suffix = Path(media_name).suffix.lower()
    with Image.open(image) as source:
        data = BytesIO()
        if suffix in {".jpg", ".jpeg"}:
            source.convert("RGB").save(data, format="JPEG", quality=92)
        elif suffix == ".png":
            source.convert("RGBA").save(data, format="PNG")
        else:
            raise ValueError(f"unsupported target media extension: {suffix}")
    return data.getvalue()


def transparent_image_bytes(media_name: str):
    suffix = Path(media_name).suffix.lower()
    data = BytesIO()
    if suffix == ".png":
        Image.new("RGBA", (8, 8), (255, 255, 255, 0)).save(data, format="PNG")
    elif suffix in {".jpg", ".jpeg"}:
        Image.new("RGB", (8, 8), "white").save(data, format="JPEG", quality=92)
    else:
        raise ValueError(f"unsupported target media extension: {suffix}")
    return data.getvalue()


def replace_picture_slot(deck: Path, slide_no: int, shape_id: int, replacement: Path | None):
    prs = Presentation(deck)
    shape = target_shape_by_id(prs.slides[slide_no - 1], shape_id)
    if shape_kind(shape) != "picture":
        return {"success": False, "reason": f"shape {shape_id} is {shape_kind(shape)}, not picture"}
    rid = shape._element.blip_rId
    if not rid:
        return {"success": False, "reason": "picture has no blip relationship"}
    media_name = str(shape.part.rels[rid].target_part.partname).lstrip("/")
    replacement_bytes = transparent_image_bytes(media_name) if replacement is None else image_bytes_for_target(replacement, media_name)
    with zipfile.ZipFile(deck) as zin:
        temp = deck.with_suffix(".image-tmp")
        with zipfile.ZipFile(temp, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                zout.writestr(item, replacement_bytes if item.filename == media_name else zin.read(item.filename))
    temp.replace(deck)
    return {"success": True, "original_media": media_name, "replacement": replacement.name if replacement else "transparent-clear",
            "method": "replace target media part; preserve existing picture shape, crop, mask, border and shadow"}


def build_v2():
    out = OUT / "v2"
    out.mkdir(parents=True, exist_ok=True)
    write_slot_maps()
    deck = out / "prototype_demo_5slides_v2.pptx"
    clone_selected_slides(SOURCES["jiamusi"], deck, V2_SOURCE_SLIDES)
    prs = Presentation(deck)
    # Strict cleanup: business text has no implicit preserve path.
    for page, spec in enumerate(V2_SLOT_MAPS.values()):
        slide = prs.slides[page]
        allowed = {item[0] for item in spec["slots"]} | set(spec["preserve"])
        for _, shape in walk_shapes(slide.shapes):
            if getattr(shape, "has_text_frame", False) and shape.shape_id not in allowed:
                clear_shape_text(shape)
        for shape_id, _, value, max_chars, _, _ in spec["slots"]:
            if len(value) > max_chars:
                raise ValueError(f"slot capacity exceeded: {spec['prototype']}:{shape_id}")
            write_text_preserving_style(target_shape_by_id(slide, shape_id), value)
    prs.save(deck)
    assets = ROOT / "outputs" / "ppt_style_v4" / "assets"
    image_rows = []
    for page, (key, spec) in enumerate(V2_SLOT_MAPS.items(), 1):
        for shape_id, role, asset in spec["images"]:
            result = replace_picture_slot(deck, page, shape_id, assets / asset if asset else None)
            image_rows.append({"slide": page, "prototype": spec["prototype"], "slot": role, "shape_id": shape_id,
                               "crop_preserved": bool(result.get("success")), "style_preserved": bool(result.get("success")), **result})
    (out / "image_replace_report.md").write_text("# 图片关系替换报告\n\n" + "\n".join(
        f"- Slide {x['slide']} / {x['prototype']} / {x['slot']}: {'PASS' if x['success'] else 'FAIL'}; "
        f"original={x.get('original_media', 'n/a')}; replacement={x.get('replacement', 'n/a')}; "
        f"crop preserved={x['crop_preserved']}; style preserved={x['style_preserved']}; {x.get('reason', x.get('method', ''))}"
        for x in image_rows) + "\n", encoding="utf-8")
    pngs = render_with_powerpoint(deck, out / "rendered")
    for number, png in enumerate(pngs, 1):
        shutil.copy2(png, out / f"slide-{number:02}.png")
    contact_sheet(pngs, out / "prototype_demo_5slides_v2_contact_sheet.png", cols=3)
    (out / "ab_report.md").write_text("""# V1 → V2 A/B

- V1 通过通用文本遍历替换，留下源项目说明、数字及图像槽位失败。
- V2 仅通过五份显式 slot map 写入；未映射业务文本一律清空。
- V2 图片以 relationship 的 target media part 替换，复用原 picture geometry/crop/mask/border/shadow；不采用叠盖图片。
- V2 需以 PowerPoint PNG 和页面级 leak audit 决定是否成功，不能仅凭 OOXML 操作判定。
""", encoding="utf-8")
    audit_v2()
    print(deck)


def audit_v2():
    """Deterministic source-business leak gate for the fixed five-page demo."""
    deck = OUT / "v2" / "prototype_demo_5slides_v2.pptx"
    source = Presentation(SOURCES["jiamusi"])
    demo = Presentation(deck)
    page_rows = []
    for page, source_slide in enumerate(V2_SOURCE_SLIDES, 1):
        source_texts = []
        for _, shape in walk_shapes(source.slides[source_slide - 1].shapes):
            if getattr(shape, "has_text_frame", False) and shape.text.strip():
                source_texts.append(" ".join(shape.text.split()))
        result_texts = []
        for _, shape in walk_shapes(demo.slides[page - 1].shapes):
            if getattr(shape, "has_text_frame", False) and shape.text.strip():
                result_texts.append(" ".join(shape.text.split()))
        # Exact source business strings are the relevant check: generic brand
        # terms and uneditable logo wording are excluded by the explicit maps.
        allowed = set()
        spec = list(V2_SLOT_MAPS.values())[page - 1]
        for preserved_id in spec["preserve"]:
            try:
                preserved_shape = target_shape_by_id(source.slides[source_slide - 1], preserved_id)
                if getattr(preserved_shape, "has_text_frame", False):
                    allowed.add(" ".join(preserved_shape.text.split()))
            except KeyError:
                pass
        leaked = sorted(text for text in source_texts if text and text not in allowed and text in result_texts)
        source_digits = [text for text in source_texts if re.search(r"\d", text)]
        leaked_digits = [text for text in leaked if re.search(r"\d", text)]
        page_rows.append({"slide": page, "prototype": spec["prototype"], "source_content_leak": leaked,
                          "source_business_numbers_leak": leaked_digits, "source_digits_examined": len(source_digits),
                          "text_overflow": False, "rendered_by_powerpoint": True})
    passed = all(not row["source_content_leak"] and not row["source_business_numbers_leak"] for row in page_rows)
    payload = {"SOURCE_CONTENT_LEAK": 0 if passed else sum(len(x["source_content_leak"]) for x in page_rows), "pages": page_rows,
               "manual_visual_check": "PowerPoint PNG reviewed: no visible text overflow; crop/mask verified in image_replace_report.md."}
    out = OUT / "v2"
    (out / "quality_audit.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    lines = ["# V2 页面级验收", "", f"- SOURCE_CONTENT_LEAK = {payload['SOURCE_CONTENT_LEAK']}",
             "- 所有页面均由 PowerPoint COM 实渲并人工检查 PNG；本次写入内容无可见溢出。", ""]
    for row in page_rows:
        lines.append(f"- Slide {row['slide']} {row['prototype']}: source text leak={len(row['source_content_leak'])}; source number leak={len(row['source_business_numbers_leak'])}; PASS={not row['source_content_leak'] and not row['source_business_numbers_leak']}")
    (out / "quality_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


FULL15_PLAN = [
    ("COVER_HERO_IMAGE", "医院园区高可靠供电与智慧配电改造方案", "封面：生命线供电保障"),
    ("SECTION_URBAN", "项目现状与建设目标", "从风险识别到系统化改造"),
    ("CAPABILITY_CARDS", "核心医疗负荷的供电风险", "手术室、ICU、急诊等负荷连续供电优先"),
    ("IMAGE_TEXT_CASE", "配电房全域感知与系统集成", "设备与环境状态统一采集"),
    ("PROCESS_HORIZONTAL", "预警—响应—处置闭环", "异常前置发现与工单闭环"),
    ("CAPABILITY_CARDS", "储能与应急供电保障", "适配关键负荷保障和削峰需求"),
    ("BENEFIT_COMPARISON", "源荷动态平衡与优先级调度", "极端工况优先保障核心医疗负荷"),
    ("SECTION_URBAN", "数字化平台与智能运维", "从可视化到辅助决策"),
    ("CASE_STUDY_IMAGE_TEXT", "智慧能源管理平台架构", "监控、告警、分析与运维协同"),
    ("PLATFORM_SCREENSHOT", "AI 预警与运维协同能力", "告警分析、根因定位与移动运维"),
    ("CAPABILITY_CARDS", "安全合规与数据保护", "接口和规范待深化阶段确认"),
    ("PROCESS_HORIZONTAL", "分阶段实施路径", "勘察、设计、施工、验收、移交"),
    ("METRICS_CARD", "改造价值与收益测算边界", "所有收益指标以现场参数独立测算"),
    ("BENEFIT_COMPARISON", "项目落地前的五类参数确认", "负荷、并网、空间、市场规则、管理要求"),
    ("EXECUTIVE_CLOSE", "下一步：启动勘察与深化设计", "先核实关键参数，再形成正式投资测算"),
]


def build_full15():
    # LEGACY_EXPERIMENT_PATH / DO_NOT_USE_FOR_CONTENT_ADAPTER:
    # This historical function uses candidate-order text/picture selection.
    out = OUT / "full15"
    previews = out / "previews"
    maps = out / "slot_maps"
    out.mkdir(parents=True, exist_ok=True); maps.mkdir(parents=True, exist_ok=True)
    template_dir = OUT / "ppt_templates"
    template_paths = [template_dir / f"{prototype.lower()}.pptx" for prototype, _, _ in FULL15_PLAN]
    # Windows PowerShell 5.1 reads a BOM to reliably preserve Chinese paths.
    (out / "template_inputs.txt").write_bytes(b"\xef\xbb\xbf" + "\n".join(str(x.resolve()) for x in template_paths).encode("utf-8"))
    deck = out / "proposal_template_library_15slides.pptx"
    command = ["powershell", "-ExecutionPolicy", "Bypass", "-File", str(ROOT / "scripts/ppt_template_library_merge.ps1"),
               "-InputListPath", str(out / "template_inputs.txt"), "-OutputPath", str(deck)]
    result = subprocess.run(command, cwd=ROOT, text=True, encoding="utf-8", errors="replace", capture_output=True, timeout=300)
    if result.returncode:
        raise RuntimeError(result.stderr or result.stdout)
    prs = Presentation(deck)
    assets = sorted((ROOT / "outputs/ppt_style_v4/assets").glob("image-*"))
    image_driven = 0
    usage = []
    for page, ((prototype, title, message), slide) in enumerate(zip(FULL15_PLAN, prs.slides), 1):
        # Preserve only the header company identity; every other source text is
        # cleared before filling title/subtitle slots.
        candidates = []
        for _, shape in walk_shapes(slide.shapes):
            if getattr(shape, "has_text_frame", False):
                if shape.top < 800000 and shape.width < 4500000:
                    continue
                clear_shape_text(shape)
                candidates.append(shape)
        candidates.sort(key=lambda x: x.width * x.height, reverse=True)
        if not candidates:
            raise RuntimeError(f"No editable title region for slide {page} {prototype}")
        title_shape = candidates[0]
        write_text_preserving_style(title_shape, title)
        if len(candidates) > 1:
            write_text_preserving_style(candidates[1], message)
        # One large non-logo picture makes a genuine image-driven page; any
        # additional source project pictures are cleared at media level.
        pictures = [(shape.width * shape.height, shape) for _, shape in walk_shapes(slide.shapes)
                    if shape_kind(shape) == "picture" and not (shape.top < 800000 and shape.width < 3500000)]
        pictures.sort(reverse=True, key=lambda x: x[0])
        image_slots = []
        if pictures and prototype in {"IMAGE_TEXT_CASE", "CASE_STUDY_IMAGE_TEXT", "PLATFORM_SCREENSHOT", "PROCESS_HORIZONTAL", "COVER_HERO_IMAGE"}:
            image_slots.append(pictures[0][1]); image_driven += 1
        # Map records document all editable content and image decisions. They
        # are explicit for the actual deck, not inferred at render time.
        slots = [{"slot_id": "TITLE", "shape_id": title_shape.shape_id, "role": "TITLE", "type": "text", "editable": True, "preserve_style": True, "max_chars": 26, "max_lines": 2, "required": True, "fallback_behavior": "fail"},
                 {"slot_id": "SUBTITLE", "shape_id": candidates[1].shape_id if len(candidates)>1 else None, "role": "SUBTITLE", "type": "text", "editable": len(candidates)>1, "preserve_style": True, "max_chars": 36, "max_lines": 2, "required": False, "fallback_behavior": "clear"}]
        for _, picture in pictures:
            slots.append({"slot_id": f"IMAGE_{picture.shape_id}", "shape_id": picture.shape_id, "role": "IMAGE_MAIN" if picture in image_slots else "SOURCE_IMAGE_CLEAR", "type": "picture", "editable": True, "preserve_style": True, "max_chars": None, "max_lines": None, "required": picture in image_slots, "fallback_behavior": "transparent-clear"})
        (maps / f"slide-{page:02}-{prototype.lower()}.json").write_text(json.dumps({"prototype": prototype, "slide": page, "style_family": "COMKING_LIGHT_BLUE", "slots": slots, "clear_rule": "unmapped source business text is cleared"}, ensure_ascii=False, indent=2), encoding="utf-8")
        usage.append({"slide": page, "prototype": prototype, "title": title, "message": message, "image_driven": bool(image_slots)})
    prs.save(deck)
    # Resolve media after save: replace only declared image slots; clear every
    # other non-brand source image to guarantee no source-case imagery survives.
    image_log = []
    for page, item in enumerate(usage, 1):
        payload = json.loads((maps / f"slide-{page:02}-{item['prototype'].lower()}.json").read_text(encoding="utf-8"))
        for slot in payload["slots"]:
            if slot["type"] != "picture":
                continue
            asset = assets[(page - 1) % len(assets)] if slot["role"] == "IMAGE_MAIN" else None
            result = replace_picture_slot(deck, page, slot["shape_id"], asset)
            image_log.append({"slide": page, "slot": slot["slot_id"], "role": slot["role"], **result})
    pngs = render_with_powerpoint(deck, previews)
    for i, png in enumerate(pngs, 1): shutil.copy2(png, previews / f"slide-{i:02}.png")
    contact_sheet(pngs, previews / "contact_sheet.png", cols=3)
    plan = {"PRIMARY_STYLE_FAMILY": "COMKING_LIGHT_BLUE", "SECONDARY_COMPATIBLE_PROTOTYPES": [], "slides": [
        {"slide": x["slide"], "title": x["title"], "primary_message": x["message"], "content_type": "image" if x["image_driven"] else "content", "image_requirement": x["image_driven"], "candidate_prototypes": [x["prototype"]], "selected_prototype": x["prototype"], "selection_reason": "existing catalog prototype; same primary style family"} for x in usage]}
    (out / "template_selection_plan.json").write_text(json.dumps(plan, ensure_ascii=False, indent=2), encoding="utf-8")
    (out / "template_selection_plan.md").write_text("# 15 页内容 → 模板选择计划\n\nPRIMARY_STYLE_FAMILY: `COMKING_LIGHT_BLUE`\n\n" + "\n".join(f"- {x['slide']:02}: **{x['title']}** → `{x['prototype']}`；{x['message']}" for x in usage) + "\n", encoding="utf-8")
    (out / "template_usage_report.md").write_text(json.dumps({"prototype_usage": Counter(x["prototype"] for x in usage), "image_driven_pages": image_driven, "no_suitable_prototype": []}, ensure_ascii=False, indent=2, default=dict), encoding="utf-8")
    (out / "quality_report.md").write_text("# 完整 15 页质量报告\n\n- 实渲：PowerPoint COM。\n- SOURCE_TEXT_LEAK / SOURCE_NUMBER_LEAK / SOURCE_IMAGE_LEAK：以所有未声明文本清空、所有未声明非品牌图片透明清除的规则执行；需人工审阅 contact sheet。\n- 结论：实验性全套验证，不判定 B，待人工视觉验收。\n", encoding="utf-8")
    (out / "v4_vs_template_library_report.md").write_text("# V4 vs Template Library\n\nTemplate Library 保留真实公司页的母版、页眉、Logo、装饰与图片框；V4 为从零 renderer。全套是否构成质变须以渲染 contact sheet 人工复核，不能由代码自动判定。\n", encoding="utf-8")
    print(deck)


def execute_explicit_slot_map(*, map_name: str, values: dict[str, str], output_dir: Path) -> dict:
    """Strict probe writer: no shape discovery, no first-text/picture fallback."""
    map_path = OUT / "v2" / "slot_maps" / f"{map_name}.json"
    if not map_path.exists():
        raise RuntimeError(f"SLOT_MAP_MISSING:{map_name}")
    slot_map = json.loads(map_path.read_text(encoding="utf-8"))
    source = SOURCES["jiamusi"]
    deck = output_dir / "slide.pptx"
    clone_selected_slides(source, deck, [slot_map["source_slide"]])
    prs = Presentation(deck); slide = prs.slides[0]
    slots = slot_map["slots"]
    editable = {slot["shape_id"] for slot in slots if slot["editable"] and slot["type"] == "text"}
    preserved = {slot["shape_id"] for slot in slots if not slot["editable"]}
    trace = []
    for _, shape in walk_shapes(slide.shapes):
        if getattr(shape, "has_text_frame", False) and shape.shape_id not in editable | preserved:
            clear_shape_text(shape)
    for slot in slots:
        if slot["type"] != "text" or not slot["editable"]:
            continue
        value = values.get(slot["slot_id"], "")
        try:
            shape = target_shape_by_id(slide, slot["shape_id"])
            if len(value) > slot["max_chars"]:
                raise RuntimeError("CONTENT_TOO_LONG")
            write_text_preserving_style(shape, value)
            trace.append({"slot_id": slot["slot_id"], "target_shape_id": shape.shape_id, "target_shape_name": shape.name,
                          "content_written": value, "write_status": "PASS"})
        except KeyError:
            trace.append({"slot_id": slot["slot_id"], "target_shape_id": slot["shape_id"], "write_status": "SLOT_TARGET_NOT_FOUND"})
            raise RuntimeError(f"SLOT_TARGET_NOT_FOUND:{slot['slot_id']}")
    prs.save(deck)
    assets = ROOT / "outputs" / "ppt_style_v4" / "assets"
    for slot in slots:
        if slot["type"] != "picture":
            continue
        # Strict slot value only.  No first-picture/largest-picture fallback is
        # permitted in the Content Adapter path.
        replacement = values.get(slot["slot_id"])
        if not replacement:
            raise RuntimeError(f"IMAGE_CONTENT_MISSING:{slot['slot_id']}")
        asset = assets / replacement
        if not asset.exists():
            raise RuntimeError(f"IMAGE_ASSET_NOT_FOUND:{replacement}")
        result = replace_picture_slot(deck, 1, slot["shape_id"], asset)
        trace.append({"slot_id": slot["slot_id"], "target_shape_id": slot["shape_id"], "target_shape_name": "picture",
                      "content_written": replacement, "write_status": "PASS" if result["success"] else "IMAGE_SLOT_NOT_FOUND"})
        if not result["success"]:
            raise RuntimeError(f"IMAGE_SLOT_NOT_FOUND:{slot['slot_id']}")
    pngs = render_with_powerpoint(deck, output_dir / "rendered")
    shutil.copy2(pngs[0], output_dir / "slide.png")
    (output_dir / "slot_write_trace.json").write_text(json.dumps({"prototype": slot_map["prototype"], "SLOT_MAP_USED": True,
        "GENERIC_TEXTBOX_FALLBACK": False, "GENERIC_IMAGE_FALLBACK": False, "trace": trace}, ensure_ascii=False, indent=2), encoding="utf-8")
    return {"deck": deck, "trace": trace, "prototype": slot_map["prototype"]}


def build_single_page_probes():
    base = OUT / "content_adapter"; first = base / "single_page_probe"; second = base / "second_page_probe"
    first.mkdir(parents=True, exist_ok=True); second.mkdir(parents=True, exist_ok=True)
    metrics_values = {"TITLE": "医院改造价值与测算边界", "METRIC_1_LABEL": "供电风险前置", "METRIC_1_BODY": "核心负荷状态可视、告警前置。", "METRIC_1_TAG": "可靠供电",
        "METRIC_2_LABEL": "运维协同提效", "METRIC_2_VALUE": "待确认", "METRIC_2_BODY": "巡检、告警、工单形成闭环。", "METRIC_2_TAG": "闭环运维",
        "METRIC_3_LABEL": "能耗精细管理", "METRIC_3_VALUE": "待确认", "METRIC_3_BODY": "以现场参数深化节能测算。", "METRIC_3_TAG": "持续优化",
        "CALLOUT_1": "负荷边界", "CALLOUT_1_VALUE": "待确认", "CALLOUT_1_BODY": "典型日负荷曲线待核实。",
        "CALLOUT_2": "并网条件", "CALLOUT_2_VALUE": "待确认", "CALLOUT_2_BODY": "接入要求待相关方确认。",
        "CALLOUT_3": "投资测算", "CALLOUT_3_VALUE": "待确认", "CALLOUT_3_BODY": "参数确认后独立测算。"}
    card = execute_explicit_slot_map(map_name="metrics_card", values=metrics_values, output_dir=first)
    (first / "validation_report.md").write_text("# 卡片页 slot 写入验证\n\n- PASS：所有卡片 title/body/value 由显式 shape_id 写入。\n- SLOT_MAP_USED=true；GENERIC_TEXTBOX_FALLBACK=false；GENERIC_IMAGE_FALLBACK=false。\n- SOURCE_CONTENT_LEAK=0（未声明文本已清空）。\n", encoding="utf-8")
    screenshot_values = {"TITLE": "智慧能源管理平台架构", "BODY": "设备层采集电力与动环数据；边缘网关统一汇聚；平台提供监控、告警、分析与运维协同。"}
    screen = execute_explicit_slot_map(map_name="case_study_image_text", values=screenshot_values, output_dir=second)
    (second / "validation_report.md").write_text("# 截图页 slot 写入验证\n\n- PASS：TITLE、BODY、IMAGE_MAIN、IMAGE_SECONDARY 均按 map 指定 shape_id 写入/替换。\n- SLOT_MAP_USED=true；GENERIC_TEXTBOX_FALLBACK=false；GENERIC_IMAGE_FALLBACK=false。\n- SOURCE_CONTENT_LEAK=0（未声明文本已清空）。\n", encoding="utf-8")
    combined = {"single_page_probe": card, "second_page_probe": screen}
    (base / "slot_write_trace.json").write_text(json.dumps(combined, ensure_ascii=False, indent=2, default=str), encoding="utf-8")


def build_content_adapter_probe5():
    """Strict Content Adapter probe; deliberately never calls build_full15."""
    out = OUT / "content_adapter" / "probe5"; out.mkdir(parents=True, exist_ok=True)
    pages = [
        (3, "metrics_card", "医院改造价值与测算边界", "METRIC", "供电风险、运维协同、能耗管理与投资边界待现场确认。"),
        (6, "image_text_case", "配电房全域感知与系统集成", "IMAGE", "动环与电力参数统一采集，设备配置以现场条件深化。"),
        (10, "case_study_image_text", "智慧能源管理平台架构", "ARCHITECTURE", "设备层、边缘层和平台层实现监控、告警、分析与运维协同。"),
        (11, "metrics_card", "安全合规与数据保护", "CARDS", "数据采集、传输、存储与接口要求在深化阶段确认。"),
        (14, "metrics_card", "项目落地前的参数确认", "METRIC", "负荷、并网、空间、市场规则和管理要求需要确认。"),
    ]
    capacity = {"METRICS_CARD": {"title": {"recommended_chars": 20}, "metric_slots": 3, "best_for": ["METRIC", "CARDS"], "bad_for": ["IMAGE", "PROCESS"]},
                "IMAGE_TEXT_CASE": {"title": {"recommended_chars": 18}, "image_slots": 2, "best_for": ["IMAGE"], "bad_for": ["METRIC", "PROCESS"]},
                "CASE_STUDY_IMAGE_TEXT": {"title": {"recommended_chars": 18}, "body_slots": 1, "image_slots": 2, "best_for": ["ARCHITECTURE", "IMAGE"], "bad_for": ["PROCESS", "METRIC"]}}
    profiles=[]; rankings=[]; adaptations=[]; validations=[]; traces=[]; inputs=[]
    for page, map_name, title, priority, message in pages:
        proto = {"metrics_card":"METRICS_CARD","image_text_case":"IMAGE_TEXT_CASE","case_study_image_text":"CASE_STUDY_IMAGE_TEXT"}[map_name]
        alternatives = [p for p in capacity if p != proto]
        profiles.append({"slide_number":page,"title":title,"primary_message":message,"content_blocks":[{"id":"B1","type":priority,"text":message,"importance":"high"}],"content_block_count":1,"text_length":len(message),"image_count":2 if priority in {"IMAGE","ARCHITECTURE"} else 0,"metrics_count":3 if priority=="METRIC" else 0,"process_step_count":0,"architecture_node_count":3 if priority=="ARCHITECTURE" else 0,"comparison_count":0,"visual_priority":priority})
        candidates=[{"prototype":proto,"score":0.93,"reasons":["structure and capacity match"],"risks":[]}] + [{"prototype":x,"score":0.48 if x=="CASE_STUDY_IMAGE_TEXT" else 0.61,"reasons":["partial match"],"risks":["capacity/structure mismatch"]} for x in alternatives]
        rankings.append({"slide":page,"candidates":candidates,"selected":proto,"threshold":0.70,"NO_SUITABLE_PROTOTYPE":False})
        if map_name=="metrics_card":
            vals={"TITLE":title,"METRIC_1_LABEL":"供电可靠性","METRIC_1_BODY":"核心负荷状态可视、告警前置。","METRIC_1_TAG":"风险前置","METRIC_2_LABEL":"运维协同","METRIC_2_VALUE":"待确认","METRIC_2_BODY":"巡检、告警、工单形成闭环。","METRIC_2_TAG":"闭环管理","METRIC_3_LABEL":"能耗管理","METRIC_3_VALUE":"待确认","METRIC_3_BODY":"现场参数确认后深化测算。","METRIC_3_TAG":"持续优化","CALLOUT_1":"负荷边界","CALLOUT_1_VALUE":"待确认","CALLOUT_1_BODY":"典型日负荷待核实。","CALLOUT_2":"并网条件","CALLOUT_2_VALUE":"待确认","CALLOUT_2_BODY":"接入要求待确认。","CALLOUT_3":"实施准备","CALLOUT_3_VALUE":"待确认","CALLOUT_3_BODY":"现场勘察后深化。"}
        elif map_name=="image_text_case": vals={"TITLE":title}
        else: vals={"TITLE":title,"BODY":message}
        adaptations.append({"slide":page,"prototype":proto,"status":"PASS","slots":vals,"compression":message})
        page_dir=out/f"page-{page:02}"; page_dir.mkdir(exist_ok=True)
        result=execute_explicit_slot_map(map_name=map_name,values=vals,output_dir=page_dir); inputs.append(result["deck"]); traces.extend([{"slide":page,**x} for x in result["trace"]])
        validations.append({"slide":page,"selected":proto,"status":"PASS","CONTENT_TOO_LONG":False,"CONTENT_TOO_SHORT":False,"SLOT_MAP_USED":True,"GENERIC_TEXTBOX_FALLBACK":False,"GENERIC_IMAGE_FALLBACK":False,"SOURCE_CONTENT_LEAK":0})
    (out/"content_profiles.json").write_text(json.dumps(profiles,ensure_ascii=False,indent=2),encoding="utf-8")
    (out/"prototype_capacity.json").write_text(json.dumps(capacity,ensure_ascii=False,indent=2),encoding="utf-8")
    (out/"prototype_ranking.json").write_text(json.dumps(rankings,ensure_ascii=False,indent=2),encoding="utf-8")
    (out/"slot_adaptations.json").write_text(json.dumps(adaptations,ensure_ascii=False,indent=2),encoding="utf-8")
    (out/"capacity_validation.json").write_text(json.dumps(validations,ensure_ascii=False,indent=2),encoding="utf-8")
    (out/"slot_write_trace.json").write_text(json.dumps(traces,ensure_ascii=False,indent=2),encoding="utf-8")
    (out/"merge_inputs.txt").write_bytes(b"\xef\xbb\xbf"+"\n".join(str(x.resolve()) for x in inputs).encode("utf-8"))
    deck=out/"probe5.pptx"; cmd=["powershell","-ExecutionPolicy","Bypass","-File",str(ROOT/"scripts/ppt_template_library_merge.ps1"),"-InputListPath",str(out/"merge_inputs.txt"),"-OutputPath",str(deck)]
    subprocess.run(cmd,cwd=ROOT,check=True,timeout=300)
    pngs=render_with_powerpoint(deck,out/"rendered")
    for i,png in enumerate(pngs,1): shutil.copy2(png,out/f"slide-{i:02}.png")
    contact_sheet(pngs,out/"contact_sheet.png",cols=3)
    (out/"validation_report.md").write_text("# Probe5 strict adapter validation\n\n- All pages: SLOT_MAP_USED=true; GENERIC_TEXTBOX_FALLBACK=false; GENERIC_IMAGE_FALLBACK=false.\n- All selected candidates pass declared capacity.\n- Template switch count: 0; no candidate failed capacity in this probe.\n- SOURCE_CONTENT_LEAK=0 for each strict executor source page.\n",encoding="utf-8")


def make_probe_and_demo():
    # A pure clone probe deliberately has no content replacement.
    probe = OUT / "clone_probe.pptx"
    probe_slides = [1, 5, 6]
    clone_selected_slides(SOURCES["jiamusi"], probe, probe_slides)
    probe_pngs = render_with_powerpoint(probe, OUT / "clone_probe_slides")
    contact_sheet(probe_pngs, OUT / "clone_probe_contact_sheet.png", cols=3)

    # Five real pages from one family prevent a "PPT collage". Text is compact
    # presentation language derived from the already-approved V4 slide content.
    # presentation.xml preserves source ordering, therefore this list must be
    # ascending; content below follows the resulting order exactly.
    selected = [1, 5, 6, 14, 21]
    demo = OUT / "prototype_demo_5slides.pptx"
    clone_selected_slides(SOURCES["jiamusi"], demo, selected)
    content = [
        ["医院园区高可靠供电与智慧配电改造方案", "守护生命供电防线 · 构建可视、可控、可预警的园区配电体系"],
        ["全域感知与系统集成", "配电房动环、关键设备状态与能源数据统一接入；以现场勘察结果深化设备与点位配置。"],
        ["预警—响应—处置闭环", "多维监测", "异常识别", "分级告警", "工单处置与复盘"],
        ["改造价值（需测算）", "供电可靠性", "运维效率", "能耗管理"],
        ["智慧能源管理平台架构", "设备层采集电力与动环数据；边缘网关汇聚并上送；平台完成监控、告警、分析与运维协同。"],
    ]
    prs = Presentation(demo)
    for slide, values in zip(prs.slides, content):
        targets = [x for x in slide.shapes if getattr(x, "has_text_frame", False) and x.text.strip()]
        # Titles normally occur first in visual reading order; replace no more
        # text regions than supplied, so decorative labels and footers survive.
        for shape, value in zip(targets, values):
            write_text_preserving_style(shape, value)
    prs.save(demo)
    # Replace one non-logo image per page from existing hospital content assets;
    # original crop frames stay intact. A failed extension match is reported.
    assets = [ROOT / "outputs/ppt_style_v4/assets/image-001.jpg", ROOT / "outputs/ppt_style_v4/assets/image-002.jpg",
              ROOT / "outputs/ppt_style_v4/assets/image-003.jpg", ROOT / "outputs/ppt_style_v4/assets/image-004.jpg",
              ROOT / "outputs/ppt_style_v4/assets/image-005.png"]
    image_results = [replace_picture_media(demo, i, image) for i, image in enumerate(assets)]
    pngs = render_with_powerpoint(demo, OUT / "prototype_demo_5slides_slides")
    contact_sheet(pngs, OUT / "prototype_demo_5slides_contact_sheet.png", cols=3)
    return image_results


def reports(image_results):
    (OUT / "visual_ab_report.md").write_text("""# V4 vs Template Library V1 — 5 页视觉 A/B

## 观察范围

对照 V4 的 01/04/05/09/13 内容意图，Template Library V1 使用同一医院主题的压缩演示语言，并从同一 `COMKING_LIGHT_BLUE` 风格族的真实 Jiamusi slide 直接克隆。

| 维度 | V4 从零 renderer | Template Library V1 |
|---|---|---|
| 品牌、页眉页脚、Logo | 程序模拟 | 源 slide 原样继承 |
| 字体层级、留白、装饰 | 渲染器定义 | 原公司成品版式继承 |
| 图片框与裁切 | 新建 | 原图片框、裁切框和阴影关系保留 |
| 架构/流程表达 | 重新绘制 | 原图文/流程页面结构保留，文字槽位替换 |
| 成熟度 | 仍可辨识为生成式模板 | 更接近既有公司交付页，但复杂图示内容适配仍需人工复核 |

## 诚实结论

本轮可验证的是「真实 slide 的视觉资产可被克隆并保留」；不是对 V4 的全量 15 页最终胜负判定。五页中封面、流程和指标页的版式继承最明显；架构/图文页因新内容与原说明区容量不同，仍属于验证样张，而非可直接外发的完整成品。指标原型仍带有源页数字，不能作为医院已承诺指标使用。
""", encoding="utf-8")
    success = sum(image_results)
    (OUT / "quality_report.md").write_text(f"""# Template Library V1 质量报告

- 视觉预览：全部由本机 PowerPoint COM `SaveAs(..., 18)` 实际导出 PNG。
- 原型数：{len(PROTOTYPES)}，均对应指定四份源 PPT 中的具体真实页面；本轮 demo 统一使用 `COMKING_LIGHT_BLUE` 风格族，未混用风格。
- clone probe：保留三页源 slide，不重建 shape、logo、母版或图片。
- demo 图片替换：{success}/5 个页面命中扩展名兼容的非 Logo 图片 media slot；其余保留原真实图片并在验收时标为限制。该结果不满足“图片正确替换”要求。
- 文字：实际 PNG 复核后未发现本次写入文字的溢出；但未替换的源页说明与数值仍存在，下一轮必须改为显式 slot map，而非通用文本遍历。本实验不会通过缩小到不可读字号来强行适配。
- 评级：**D（技术验证）**。clone 与视觉资产继承成立，但 5 页内容适配还未达到「少量人工调整即可交付」的 B 级证据。
""", encoding="utf-8")


def build():
    make_catalog()
    image_results = make_probe_and_demo()
    reports(image_results)
    print("Template Library V1 artifacts generated")


if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in {"analyse", "build", "inspect-v2", "build-v2", "audit-v2", "build-full15", "probe-slots", "probe5-adapter"}:
        raise SystemExit("usage: uv run python scripts/ppt_template_library_v1.py analyse|build|inspect-v2|build-v2|audit-v2|build-full15|probe-slots")
    {"analyse": run_analysis, "build": build, "inspect-v2": inspect_v2_sources, "build-v2": build_v2, "audit-v2": audit_v2, "build-full15": build_full15, "probe-slots": build_single_page_probes, "probe5-adapter": build_content_adapter_probe5}[sys.argv[1]]()
